### ISSUE TITLE
Bad syntax tests

### ISSUE THREAD

**Issue by jayvdb** [xZise/flake8-future-import#2]
The Python repo has some lovely bad syntax test cases in `Lib/test/badsyntax_future*` https://hg.python.org/cpython/file/tip/Lib/test

This plugin raises ValueError exceptions for many of them, which dont turn out very pretty in flake8, as it doesnt show the error at all. e.g.

```
$ flake8 Lib/test/badsyntax_future3.py 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 74, in process_main
    self._process_main()
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 50, in _process_main
    self.input_file(filename)
  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 95, in input_file
```

The lack of good output for these files could be blamed on flake8/pep8.  maybe they should catch these exceptions and explain the failure better to the end-user.

Some at least you may find are interesting enough to be new error codes.

Anyway, it looks like only file '10' is showing an error correctly; here is the full output

```
$ flake8 Lib/test/badsyntax_future*.py 
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 74, in process_main
    self._process_main()
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 50, in _process_main
    self.input_file(filename)
  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 95, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/lib/python2.7/site-packages/pep8-1.6.3a0-py2.7.egg/pep8.py", line 1571, in check_all
    self.check_ast()
  File "/usr/lib/python2.7/site-packages/pep8-1.6.3a0-py2.7.egg/pep8.py", line 1518, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/usr/lib/python2.7/site-packages/flake8_future_import.py", line 106, in run
    yield self._generate_error(alias.name, import_node.lineno, True)
  File "/usr/lib/python2.7/site-packages/flake8_future_import.py", line 90, in _generate_error
    code = 10 + self.AVAILABLE_IMPORTS.index(future_import)
ValueError: tuple.index(x): x not in tuple
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 74, in process_main
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 74, in process_main
    self._process_main()
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 50, in _process_main
    self.input_file(filename)
  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 95, in input_file
    self._process_main()
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 50, in _process_main
    self.input_file(filename)
  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 95, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/lib/python2.7/site-packages/pep8-1.6.3a0-py2.7.egg/pep8.py", line 1571, in check_all
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/lib/python2.7/site-packages/pep8-1.6.3a0-py2.7.egg/pep8.py", line 1571, in check_all
    self.check_ast()
  File "/usr/lib/python2.7/site-packages/pep8-1.6.3a0-py2.7.egg/pep8.py", line 1518, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/usr/lib/python2.7/site-packages/flake8_future_import.py", line 106, in run
    self.check_ast()
  File "/usr/lib/python2.7/site-packages/pep8-1.6.3a0-py2.7.egg/pep8.py", line 1518, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/usr/lib/python2.7/site-packages/flake8_future_import.py", line 106, in run
    yield self._generate_error(alias.name, import_node.lineno, True)
  File "/usr/lib/python2.7/site-packages/flake8_future_import.py", line 90, in _generate_error
    code = 10 + self.AVAILABLE_IMPORTS.index(future_import)
ValueError: tuple.index(x): x not in tuple
    yield self._generate_error(alias.name, import_node.lineno, True)
  File "/usr/lib/python2.7/site-packages/flake8_future_import.py", line 90, in _generate_error
    code = 10 + self.AVAILABLE_IMPORTS.index(future_import)
ValueError: tuple.index(x): x not in tuple
Lib/test/badsyntax_future10.py:1:1: FI10 __future__ import "division" missing
Lib/test/badsyntax_future10.py:1:1: FI12 __future__ import "with_statement" missing
Lib/test/badsyntax_future10.py:1:1: FI14 __future__ import "unicode_literals" missing
Lib/test/badsyntax_future10.py:1:1: FI15 __future__ import "generator_stop" missing
Lib/test/badsyntax_future10.py:1:1: FI51 __future__ import "absolute_import" present
Lib/test/badsyntax_future10.py:3:1: FI53 __future__ import "print_function" present
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 74, in process_main
    self._process_main()
  File "/usr/lib/python2.7/site-packages/flake8/reporter.py", line 50, in _process_main
    self.input_file(filename)
  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 95, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/lib/python2.7/site-packages/pep8-1.6.3a0-py2.7.egg/pep8.py", line 1571, in check_all
```

**Comment by xZise** [comment]
Okay the failure for the third bad syntax is because it's using unknown future imports. In theory I could check them too, but there is the issue that I don't actually support the very old ones like `nested_scopes`. Maybe I should include them somewhere and add another error code when the future import is unknown.

**Comment by xZise** [comment]
Okay I checked and `flake8` does not report unknown future imports. I'll release 0.3.2 which at least shouldn't crash and with 0.4.0 a new code (`FI90`) will report any unknown codes. I might then add the two skipped codes (`nested_scops` and `generators`) so it probably will also break the existing error codes.

And to be honest I need to check against all bad codes.

**Comment by xZise** [comment]
Okay 9567fe1 now actually uses the bad syntax files and tests them. I'll upload 0.3.2 shortly then.
