### ISSUE TITLE
Question: How does this plugin interact with Flake8's diff option?

### ISSUE THREAD

**Issue by DylanYoung** [xZise/flake8-future-import#23]
I suspect this affects issue #1, Pull Request #3, and Pull Request #11

Also I'm getting an error when trying to use this plugin:

```
Traceback (most recent call last):
  ...
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/flake8/plugins/manager.py", line 489, in register_options
    list(self.manager.map(register_and_enable))
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/flake8/plugins/manager.py", line 297, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/flake8/plugins/manager.py", line 485, in register_and_enable
    call_register_options(plugin)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/flake8/plugins/manager.py", line 397, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/flake8/plugins/manager.py", line 216, in register_options
    add_options(optmanager)
  File "/Users/caseymeijer/envs/iris/lib/python2.7/site-packages/flake8_future.py", line 30, in add_options
    parser.config_options.append('future-imports')
AttributeError: 'OptionManager' object has no attribute 'config_options'
```

Have you seen this before?  Seems like a common issue with old flake8 plugins, but this one seems maintained....

**Comment by DylanYoung** [comment]
I had accidentally installed flake8-import, so don't worry about that error, lol.
