### ISSUE TITLE
No support for flake8 3.0

### ISSUE THREAD

**Issue by The-Compiler** [xZise/flake8-future-import#8]
I just tried using this with flake8 3.0.0b1 and got:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 292, in run
    self._run(argv)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 278, in _run
    self.initialize(argv)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 269, in initialize
    self.register_plugin_options()
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 149, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 378, in register_options
    list(self.manager.map(call_register_options))
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 252, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 348, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 198, in register_options
    add_options(optmanager)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8_future_import.py", line 60, in add_options
    cls.add_arguments(Wrapper())
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8_future_import.py", line 102, in add_arguments
    help='Do only apply to files which not only have '
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8_future_import.py", line 57, in add_argument
    parser.config_options.append(opt.lstrip('-'))
AttributeError: 'OptionManager' object has no attribute 'config_options'
```

flake8 documentation about the change: http://flake8.pycqa.org/en/latest/plugin-development/cross-compatibility.html#option-handling-on-flake8-2-and-3

Related fixes in pep8-naming:

https://github.com/PyCQA/pep8-naming/commit/b4c3ebd4884bac27fae56aa45c6f9e7c5b5ea5a0
https://github.com/PyCQA/pep8-naming/commit/dd623fcd76db58922a511578ff5d14ce741f9636

**Comment by xZise** [comment]
Thank you for the notification.

I noticed there are several other things which I need to fix (e.g. FI90 is basically the same as F999). So over time fixes will trickle in and among them there will be a fix for this issue. The `flake8-3` branch already contains a fix but because Travis currently requires other issues to be fixed as well, it won't be merged yet.

**Comment by xZise** [comment]
Okay with version 0.4.2 this should be fixed. It has been released to pypi.

**Comment by The-Compiler** [comment]
Hmm, it seems like config options now are broken for flake8 2.6.2? I get `unknown option 'min-version' ignored`.

Note flake8 3.0 isn't released yet, so I think 2 compatibility should really be kept for now...

**Comment by xZise** [comment]
Of course I didn't wanted to remove flake8 version 2 compatibility. I'll take a look into it.

**Comment by xZise** [comment]
Okay found the reason, but not sure when I can upload a fix. As a workaround you could use `min_version` but with 0.4.3 this won't work anymore then.

**Comment by The-Compiler** [comment]
No worries, I just blacklisted 0.4.2 for now - thanks for taking a look!

**Comment by xZise** [comment]
Anyway 0.4.3 is up which should resolve that issue.

**Comment by The-Compiler** [comment]
I can confirm - thank you! :+1:
